# PyTorch Linear Regression

In [1]:
# Import NumPy, PyTorch
import torch
import numpy as np

In [2]:
# Create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)  # weights; requires_grad because the optimizer will update w
b = torch.tensor(5., requires_grad=True)  # bias;

In [3]:
print(x)
print(w)
print(b)

tensor(3.)
tensor(4., requires_grad=True)
tensor(5., requires_grad=True)


In [5]:
# Combine tensors with arithmetic operations
y = w * x + b
print(y)

tensor(17., grad_fn=<AddBackward0>)


In [6]:
# Compute gradients
y.backward()

In [10]:
# Display gradients
print(f'dy/dw:', w.grad)
print(f'dy/db:', b.grad)

dy/dw: tensor(3.)
dy/db: tensor(1.)


## Problem Statement

The model will predict crop yields for 2 different fruits: apples, oranges.
The input variables are average temperature, rainfall, humidity.

In [15]:
# Input data (temperature, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70]], dtype='float32')

In [16]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                   [81, 101],
                   [119, 133],
                   [22, 37],
                   [103, 119]], dtype='float32')

Before building a model, *input* and *target* need to be converted to PyTorch tensors.

In [17]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Linear regression from scratch 

Initialize weights and biases with random values

In [22]:
# Random initialization of w and b
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.3389, -1.5558,  0.0352],
        [-0.9144, -0.9678, -0.8755]], requires_grad=True)
tensor([ 0.8349, -1.7029], requires_grad=True)


The model is simply a function that performs a matrix multiplication of *input* and *w*, and adds the bias *b*.

In [23]:
# Define the model
def model(x):
    return x @ w.t() + b

In [24]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ -77.1498, -170.9441],
        [-102.9817, -226.1129],
        [-176.1134, -261.7185],
        [ -30.1957, -168.9836],
        [-122.6715, -218.9905]], grad_fn=<AddBackward0>)


In [25]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


The model is pretty far off due to random initialization.

##  Loss function

In [40]:
# MSE
def mse(pred, act):
    diff = pred - act
    return torch.sum(diff * diff) / diff.numel()

In [41]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(66984.8594, grad_fn=<DivBackward0>)


In [ ]:
# Compute gradients w.r.t. w and b. The gradients are stored in w.grad() and b.grad()
loss.backward()

In [45]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 0.3389, -1.5558,  0.0352],
        [-0.9144, -0.9678, -0.8755]], requires_grad=True)
tensor([[-14606.4873, -17713.1016, -10469.0195],
        [-25205.6777, -27825.1719, -17094.0469]])


In [46]:
# Gradients for bias
print(b)
print(b.grad)

tensor([ 0.8349, -1.7029], requires_grad=True)
tensor([-178.0224, -301.3499])


In [47]:
# Reset gradients before moving forward
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


## Adjust weights and biases using gradient descent

1. Generate predictions
2. Calculate loss
3. Calculate gradients of loss w.r.t. weights and biases
4. Update weights and biases by subtracting a small quantity proportional to gradient
5. Reset gradients to zero

In [48]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ -77.1498, -170.9441],
        [-102.9817, -226.1129],
        [-176.1134, -261.7185],
        [ -30.1957, -168.9836],
        [-122.6715, -218.9905]], grad_fn=<AddBackward0>)


In [49]:
# Calculate loss
loss = mse(preds, targets)
print(loss)

tensor(66984.8594, grad_fn=<DivBackward0>)


In [50]:
# Calculate gradient
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-14606.4873, -17713.1016, -10469.0195],
        [-25205.6777, -27825.1719, -17094.0469]])
tensor([-178.0224, -301.3499])


In [52]:
# Update weights and biases
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [54]:
print(w)
print(b)

tensor([[ 0.4849, -1.3786,  0.1399],
        [-0.6624, -0.6895, -0.7046]], requires_grad=True)
tensor([ 0.8367, -1.6999], requires_grad=True)


With the new weights and biases, the model should have a smaller loss

In [55]:
# Calculate new predictions and new loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(45691.1289, grad_fn=<DivBackward0>)


## Train for multiple epochs

To reduce the loss further, repeat the process of adjusting weights and biases using the gradients multiple times.

In [81]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [82]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(5.0539, grad_fn=<DivBackward0>)


In [83]:
# Print predictions
print(preds)

tensor([[ 57.2880,  70.2838],
        [ 82.4022,  98.7401],
        [118.0539, 137.3833],
        [ 20.9978,  38.3174],
        [102.4732, 114.6873]], grad_fn=<AddBackward0>)


In [69]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
