In [1]:
import numpy as np

In [2]:
np.random.seed(1)

In [3]:
X = np.random.choice(10, [3, 3])
X

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [4]:
X1 = np.random.choice(10, [1, 100])
X2 = X1**2

In [5]:
X = np.concatenate((X1, X2), axis=0)
X

array([[ 9,  2,  4,  5,  2,  4,  2,  4,  7,  7,  9,  1,  7,  0,  6,  9,
         9,  7,  6,  9,  1,  0,  1,  8,  8,  3,  9,  8,  7,  3,  6,  5,
         1,  9,  3,  4,  8,  1,  4,  0,  3,  9,  2,  0,  4,  9,  2,  7,
         7,  9,  8,  6,  9,  3,  7,  7,  4,  5,  9,  3,  6,  8,  0,  2,
         7,  7,  9,  7,  3,  0,  8,  7,  7,  1,  1,  3,  0,  8,  6,  4,
         5,  6,  2,  5,  7,  8,  4,  4,  7,  7,  4,  9,  0,  2,  0,  7,
         1,  7,  9,  8],
       [81,  4, 16, 25,  4, 16,  4, 16, 49, 49, 81,  1, 49,  0, 36, 81,
        81, 49, 36, 81,  1,  0,  1, 64, 64,  9, 81, 64, 49,  9, 36, 25,
         1, 81,  9, 16, 64,  1, 16,  0,  9, 81,  4,  0, 16, 81,  4, 49,
        49, 81, 64, 36, 81,  9, 49, 49, 16, 25, 81,  9, 36, 64,  0,  4,
        49, 49, 81, 49,  9,  0, 64, 49, 49,  1,  1,  9,  0, 64, 36, 16,
        25, 36,  4, 25, 49, 64, 16, 16, 49, 49, 16, 81,  0,  4,  0, 49,
         1, 49, 81, 64]])

In [6]:
Y = X1 + X2 + 10
Y

array([[100,  16,  30,  40,  16,  30,  16,  30,  66,  66, 100,  12,  66,
         10,  52, 100, 100,  66,  52, 100,  12,  10,  12,  82,  82,  22,
        100,  82,  66,  22,  52,  40,  12, 100,  22,  30,  82,  12,  30,
         10,  22, 100,  16,  10,  30, 100,  16,  66,  66, 100,  82,  52,
        100,  22,  66,  66,  30,  40, 100,  22,  52,  82,  10,  16,  66,
         66, 100,  66,  22,  10,  82,  66,  66,  12,  12,  22,  10,  82,
         52,  30,  40,  52,  16,  40,  66,  82,  30,  30,  66,  66,  30,
        100,  10,  16,  10,  66,  12,  66, 100,  82]])

In [7]:
class Relu():
    def forward(self, Z):
        self.A = np.maximum(Z, 0)        
        return self.A
    
    def backward(self, grads_in):
        pass
        # self.grads = 
    
    def __call__(self, Z):
        return self.forward(Z)

In [8]:
# w = np.array([[1.],[2.]])
# b = 2.
X = np.array([[1.,2.,-1.],[3.,4.,-3.2]])
Y = np.array([[1,0,1]])

In [9]:
np.random.randn(1, 2).T

array([[-1.2915627 ],
       [-0.84824392]])

In [10]:
np.random.randn(2, 1)

array([[-0.16659957],
       [ 0.91719602]])

In [11]:
np.array([[1.], [2.]])

array([[1.],
       [2.]])

In [12]:
np.array([10., 5.]) - np.array([[1.], [2.]])

array([[9., 4.],
       [8., 3.]])

In [13]:
class Linear():
    def __init__(self, n_out, n_in, initmethod='gauss'):
        self.n_in = n_in
        self.n_out = n_out
        self.m = 0  # gets a proper value in forward
        self.b = np.zeros([1, n_out])
        self.W = np.zeros([n_in, n_out])
        self.b_grad = np.zeros([n_out, 1])
        self.W_grad = np.zeros([n_out, n_in])
        if initmethod == 'gauss':
            self.W = np.random.randn(n_out, n_in) * 0.01
        elif initmethod == 'constant':
            self.W = np.array([2., 1.])
            self.b = 2.
        
    def forward(self, A_in):
        self.A_in = A_in
        self.m = self.A_in.shape[1]
        self.Z = np.add(np.dot(self.W, self.A_in), self.b)
        return self.Z
    
    def backward(self, grads_in):
        self.grads_W = 1/self.m * np.dot(self.A_in, grads_in.T )
        self.grads_b = np.mean(grads_in, keepdims=True)
    
    def __call__(self, A):
        return self.forward(A)

In [14]:
class Sigmoid():
    def forward(self, Z):
        self.A = np.divide(1, np.add(1, np.exp(-Z)))
        return self.A
    
    def backward(self, grads_in):
        self.grads = grads_in * (self.A * (1-self.A))
        return self.grads
    
    def __call__(self, Z):
        return self.forward(Z)

In [15]:
class Loss():
    def forward(self, A, Y):
        self.A = A
        self.Y = Y
        self.L = -np.mean(Y*np.log(A) + (1-Y)*np.log(1-A))
        return self.L
    
    def backward(self):
        self.grads = np.divide(self.A-self.Y, np.multiply(self.A, (1-self.A)))
        return self.grads

In [16]:
loss = Loss()
lin1 = Linear(1, 2, initmethod="constant")
act1 = Sigmoid()

In [36]:
loss.forward(act1(lin1(X)), Y)

5.801545319394553

In [37]:
lin1.backward(act1.backward(loss.backward()))

In [17]:
num_iterations = 100
learning_rate = 0.009

In [18]:
costs = []

In [19]:
def optimize():
    for i in range(num_iterations):
        cost = loss.forward(act1(lin1(X)), Y)
        costs.append(cost)        
        lin1.backward(act1.backward(loss.backward()))
        lin1.W = lin1.W - learning_rate*lin1.grads_W
        lin1.b = lin1.b - learning_rate*lin1.grads_b
    print(f'lin1.W: {lin1.W}')
    print(f'lin1.b: {lin1.b}')
    print(f'lin1.W_grad: {lin1.grads_W}')
    print(f'lin1.b_grad: {lin1.grads_b}')
    print(f'cost: {cost}')

In [20]:
optimize()

lin1.W: [[ 1.16125358  0.34965789]
 [ 0.03495158 -0.42403486]]
lin1.b: [[1.90920401]]
lin1.W_grad: [[0.8575548  0.29161286]
 [1.94800861 0.48855223]]
lin1.b_grad: [[0.09976993]]
cost: 1.3164470991568429


In [78]:
lin1 = Linear(3, 1)
act1 = Relu()
lin2 = Linear(4, 1)
act2 = Sigmoid()

In [62]:
lin1.grads_W.shape

(2, 1)

In [63]:
lin1.W.shape

(2, 1)

In [79]:
A1 = act1(lin1(X))

In [80]:
A2 = act2(lin2(A1))

In [81]:
A2

array([[0.99996855, 0.202798  , 0.15027745]])